- name: Compile Arduino Sketches
    uses: arduino/compile-sketches@v1.0.0
    with:
        fqbn: 'arduino:megaavr'
        libraries: |
            - name: ArduinoJson
        sketch-paths: 
            - "nano_every"
