name: Compile Arduino Sketches
on: [push]

jobs:
  build:    
    strategy:
      matrix:
        board: ["arduino:megaavr", "arduino:mbed_nano"]
        include:
          - board: arduino:megaavr
            libraries: ArduinoJson
            sketch-path: ./nano_every
          - board: arduino:mbed_nano
            libraries: ArduinoJson Arduino_LPS22HB Arduino_HTS221 Arduino_LSM9DS1
            sketch-path: ./nano_ble_sense
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.board }}
      - name: Install libraries
        run: |
          arduino-cli lib install ${{ matrix.libraries }}
      - name: Compile Sketch
        working-directory: .
        run: arduino-cli compile --fqbn ${{ matrix.board }} -e ${{ matrix.sketch-path }}
      - name: Upload bin
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}
          path: ${{ matrix.sketch-path }}/build/${{ matrix.board }}/*.ino.bin
