- name: Compile Arduino Sketches
    uses: arduino/compile-sketches@v1.0.0
    with:
        fqbn: 'arduino:arduino:mbed_nano'
        libraries: |
            - name: ArduinoJson
            - name: Arduino_LPS22HB
            - name: Arduino_HTS221
            - name: Arduino_LSM9DS1
        sketch-paths: 
            - "nano_ble_sense"
